# Rakefile
require 'bundler/gem_tasks'  
require 'rake/clean'

CLEAN.include('ext/**/*{.o,.log,.so,.bundle}')  
CLEAN.include('ext/**/Makefile')  
CLOBBER.include('lib/*{.so,.bundle}')
CLOBBER.include('ext/**/*.cxx')

desc 'Generate cxx source files from SWIG.'
task :swig do  
  Dir.chdir("ext/papillon") do
    sh "swig -I$PAPILLON_INSTALL_DIR/include/PapillonCore -o papillon.cxx -ruby -c++ ../../Papillon.i"
  end
end

desc 'Build the extension.'
task :build do
  Dir.chdir("ext/papillon") do
    ruby "extconf.rb"
    sh "make"
  end
end

desc 'Build the extension including fresh SWIG C++ file.'
task :full_build => [:swig, :build]