/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PapillonSDK {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PapillonSDK(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PapillonSDK obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PapillonSDK(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static PResult Init(PString listPluginPathsSeparatedBySemicolon) {
    return new PResult(PapillonCoreJavaJNI.PapillonSDK_Init__SWIG_0(PString.getCPtr(listPluginPathsSeparatedBySemicolon), listPluginPathsSeparatedBySemicolon), true);
  }

  public static PResult Init() {
    return new PResult(PapillonCoreJavaJNI.PapillonSDK_Init__SWIG_1(), true);
  }

  public static PResult End() {
    return new PResult(PapillonCoreJavaJNI.PapillonSDK_End(), true);
  }

}
