/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PByteArrayOutputStream extends POutputStream {
  private long swigCPtr;

  protected PByteArrayOutputStream(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PByteArrayOutputStream_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PByteArrayOutputStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PByteArrayOutputStream(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PByteArrayOutputStream() {
    this(PapillonCoreJavaJNI.new_PByteArrayOutputStream__SWIG_0(), true);
  }

  public PByteArrayOutputStream(PByteArray byteArray) {
    this(PapillonCoreJavaJNI.new_PByteArrayOutputStream__SWIG_1(PByteArray.getCPtr(byteArray), byteArray), true);
  }

  public PByteArray GetByteArray() {
    return new PByteArray(PapillonCoreJavaJNI.PByteArrayOutputStream_GetByteArray(swigCPtr, this), true);
  }

}
