/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PDescriptor extends PSerialisationInterface {
  private long swigCPtr;

  protected PDescriptor(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PDescriptor_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PDescriptor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PDescriptor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PDescriptor() {
    this(PapillonCoreJavaJNI.new_PDescriptor__SWIG_0(), true);
  }

  public PDescriptor(PObjectType objectType, PGuid describeId, PGuid descriptorId) {
    this(PapillonCoreJavaJNI.new_PDescriptor__SWIG_1(PObjectType.getCPtr(objectType), objectType, PGuid.getCPtr(describeId), describeId, PGuid.getCPtr(descriptorId), descriptorId), true);
  }

  public PDescriptor(PObjectType objectType, PGuid describeId) {
    this(PapillonCoreJavaJNI.new_PDescriptor__SWIG_2(PObjectType.getCPtr(objectType), objectType, PGuid.getCPtr(describeId), describeId), true);
  }

  public PDescriptor(PDescriptor other) {
    this(PapillonCoreJavaJNI.new_PDescriptor__SWIG_3(PDescriptor.getCPtr(other), other), true);
  }

  public PObjectType GetObjectType() {
    return new PObjectType(PapillonCoreJavaJNI.PDescriptor_GetObjectType(swigCPtr, this), false);
  }

  public PGuid GetDescribeId() {
    return new PGuid(PapillonCoreJavaJNI.PDescriptor_GetDescribeId(swigCPtr, this), false);
  }

  public PGuid GetDescriptorId() {
    return new PGuid(PapillonCoreJavaJNI.PDescriptor_GetDescriptorId(swigCPtr, this), false);
  }

  public boolean IsEmpty() {
    return PapillonCoreJavaJNI.PDescriptor_IsEmpty(swigCPtr, this);
  }

  public void SetDescriptor(PByteArray value) {
    PapillonCoreJavaJNI.PDescriptor_SetDescriptor(swigCPtr, this, PByteArray.getCPtr(value), value);
  }

  public boolean GetDescriptor(PByteArray value) {
    return PapillonCoreJavaJNI.PDescriptor_GetDescriptor(swigCPtr, this, PByteArray.getCPtr(value), value);
  }

  public PProperties SetProperties() {
    return new PProperties(PapillonCoreJavaJNI.PDescriptor_SetProperties(swigCPtr, this), true);
  }

  public PProperties GetProperties() {
    return new PProperties(PapillonCoreJavaJNI.PDescriptor_GetProperties(swigCPtr, this), true);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PDescriptor_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PDescriptor_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PDescriptor_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PDescriptor_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PDescriptor_ToString(swigCPtr, this), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PDescriptor_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

}
