/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PDescriber {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PDescriber(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PDescriber obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PDescriber(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static PResult Create(PString parameters, PDescriber describer) {
    return new PResult(PapillonCoreJavaJNI.PDescriber_Create(PString.getCPtr(parameters), parameters, PDescriber.getCPtr(describer), describer), true);
  }

  public PDescriber() {
    this(PapillonCoreJavaJNI.new_PDescriber__SWIG_0(), true);
  }

  public PDescriber(PDescriber other) {
    this(PapillonCoreJavaJNI.new_PDescriber__SWIG_1(PDescriber.getCPtr(other), other), true);
  }

  public PString GetName() {
    return new PString(PapillonCoreJavaJNI.PDescriber_GetName(swigCPtr, this), true);
  }

  public PObjectType GetObjectType() {
    return new PObjectType(PapillonCoreJavaJNI.PDescriber_GetObjectType(swigCPtr, this), true);
  }

  public PGuid GetDescribeId() {
    return new PGuid(PapillonCoreJavaJNI.PDescriber_GetDescribeId(swigCPtr, this), true);
  }

  public PResult Describe(PExampleSet exampleSet, PDescription description) {
    return new PResult(PapillonCoreJavaJNI.PDescriber_Describe__SWIG_0(swigCPtr, this, PExampleSet.getCPtr(exampleSet), exampleSet, PDescription.getCPtr(description), description), true);
  }

  public PResult Describe(PDetection example, PString name, PGuid identityId, PDescription description) {
    return new PResult(PapillonCoreJavaJNI.PDescriber_Describe__SWIG_1(swigCPtr, this, PDetection.getCPtr(example), example, PString.getCPtr(name), name, PGuid.getCPtr(identityId), identityId, PDescription.getCPtr(description), description), true);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PDescriber_ToString(swigCPtr, this), true);
  }

  public void SetPimpl(SWIGTYPE_p_papillon__PDescriberInterface arg0) {
    PapillonCoreJavaJNI.PDescriber_SetPimpl(swigCPtr, this, SWIGTYPE_p_papillon__PDescriberInterface.getCPtr(arg0));
  }

}
