/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PDetection extends PSerialisationInterface {
  private long swigCPtr;

  protected PDetection(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PDetection_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PDetection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PDetection(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PDetection() {
    this(PapillonCoreJavaJNI.new_PDetection__SWIG_0(), true);
  }

  public PDetection(PObjectType objectType, PGuid detectorId, PFrame frame, PFeatureMap featureMap, float reliability) {
    this(PapillonCoreJavaJNI.new_PDetection__SWIG_1(PObjectType.getCPtr(objectType), objectType, PGuid.getCPtr(detectorId), detectorId, PFrame.getCPtr(frame), frame, PFeatureMap.getCPtr(featureMap), featureMap, reliability), true);
  }

  public PDetection(PGuid objectId, PGuid detectorId, PFrame frame, PObjectType objectType, PTrack track, PFeatureMap featureMap, float confidence) {
    this(PapillonCoreJavaJNI.new_PDetection__SWIG_2(PGuid.getCPtr(objectId), objectId, PGuid.getCPtr(detectorId), detectorId, PFrame.getCPtr(frame), frame, PObjectType.getCPtr(objectType), objectType, PTrack.getCPtr(track), track, PFeatureMap.getCPtr(featureMap), featureMap, confidence), true);
  }

  public PDetection(PDetection other) {
    this(PapillonCoreJavaJNI.new_PDetection__SWIG_3(PDetection.getCPtr(other), other), true);
  }

  public boolean IsValid() {
    return PapillonCoreJavaJNI.PDetection_IsValid(swigCPtr, this);
  }

  public PObjectType GetObjectType() {
    return new PObjectType(PapillonCoreJavaJNI.PDetection_GetObjectType(swigCPtr, this), false);
  }

  public PGuid GetObjectId() {
    return new PGuid(PapillonCoreJavaJNI.PDetection_GetObjectId(swigCPtr, this), false);
  }

  public PGuid GetDetectorId() {
    return new PGuid(PapillonCoreJavaJNI.PDetection_GetDetectorId(swigCPtr, this), false);
  }

  public PTrack GetTrack() {
    return new PTrack(PapillonCoreJavaJNI.PDetection_GetTrack__SWIG_0(swigCPtr, this), false);
  }

  public PFrame GetFrame() {
    return new PFrame(PapillonCoreJavaJNI.PDetection_GetFrame(swigCPtr, this), false);
  }

  public PFeatureMap GetFeatureMap() {
    return new PFeatureMap(PapillonCoreJavaJNI.PDetection_GetFeatureMap__SWIG_0(swigCPtr, this), false);
  }

  public float GetConfidence() {
    return PapillonCoreJavaJNI.PDetection_GetConfidence(swigCPtr, this);
  }

  public void SetInvalid() {
    PapillonCoreJavaJNI.PDetection_SetInvalid(swigCPtr, this);
  }

  public void SetObjectType(PObjectType objectType) {
    PapillonCoreJavaJNI.PDetection_SetObjectType(swigCPtr, this, PObjectType.getCPtr(objectType), objectType);
  }

  public void SetDetectorId(PGuid detectorId) {
    PapillonCoreJavaJNI.PDetection_SetDetectorId(swigCPtr, this, PGuid.getCPtr(detectorId), detectorId);
  }

  public void SetFrame(PFrame frame) {
    PapillonCoreJavaJNI.PDetection_SetFrame(swigCPtr, this, PFrame.getCPtr(frame), frame);
  }

  public void SetFeatureMap(PFeatureMap featureMap) {
    PapillonCoreJavaJNI.PDetection_SetFeatureMap(swigCPtr, this, PFeatureMap.getCPtr(featureMap), featureMap);
  }

  public void SetConfidence(float reliability) {
    PapillonCoreJavaJNI.PDetection_SetConfidence(swigCPtr, this, reliability);
  }

  public void SetTrack(PTrack track) {
    PapillonCoreJavaJNI.PDetection_SetTrack(swigCPtr, this, PTrack.getCPtr(track), track);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PDetection_ToString(swigCPtr, this), true);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PDetection_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PDetection_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PDetection_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PDetection_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PDetection_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

  public static PDetection getC_BAD() {
    long cPtr = PapillonCoreJavaJNI.PDetection_C_BAD_get();
    return (cPtr == 0) ? null : new PDetection(cPtr, false);
  }

}
