/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PDetectionList extends PSerialisationInterface {
  private long swigCPtr;

  protected PDetectionList(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PDetectionList_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PDetectionList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PDetectionList(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PDetectionList() {
    this(PapillonCoreJavaJNI.new_PDetectionList__SWIG_0(), true);
  }

  public PDetectionList(PDetectionList other) {
    this(PapillonCoreJavaJNI.new_PDetectionList__SWIG_1(PDetectionList.getCPtr(other), other), true);
  }

  public void Clear() {
    PapillonCoreJavaJNI.PDetectionList_Clear(swigCPtr, this);
  }

  public boolean IsEmpty() {
    return PapillonCoreJavaJNI.PDetectionList_IsEmpty(swigCPtr, this);
  }

  public int Size() {
    return PapillonCoreJavaJNI.PDetectionList_Size(swigCPtr, this);
  }

  public void Add(PDetection e) {
    PapillonCoreJavaJNI.PDetectionList_Add(swigCPtr, this, PDetection.getCPtr(e), e);
  }

  public PDetection Get(int n) {
    return new PDetection(PapillonCoreJavaJNI.PDetectionList_Get(swigCPtr, this, n), true);
  }

  public void RemoveSmallest(int minWidthBBox, int minHeightBBox, PString objectType) {
    PapillonCoreJavaJNI.PDetectionList_RemoveSmallest(swigCPtr, this, minWidthBBox, minHeightBBox, PString.getCPtr(objectType), objectType);
  }

  public void Keep(PSizei minBoundingBox, PSizei maxBoundingBox, PString objectType, int maxNumber) {
    PapillonCoreJavaJNI.PDetectionList_Keep__SWIG_0(swigCPtr, this, PSizei.getCPtr(minBoundingBox), minBoundingBox, PSizei.getCPtr(maxBoundingBox), maxBoundingBox, PString.getCPtr(objectType), objectType, maxNumber);
  }

  public void Keep(PSizei minBoundingBox, PSizei maxBoundingBox, PString objectType) {
    PapillonCoreJavaJNI.PDetectionList_Keep__SWIG_1(swigCPtr, this, PSizei.getCPtr(minBoundingBox), minBoundingBox, PSizei.getCPtr(maxBoundingBox), maxBoundingBox, PString.getCPtr(objectType), objectType);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PDetectionList_ToString(swigCPtr, this), true);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PDetectionList_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PDetectionList_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PDetectionList_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PDetectionList_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PDetectionList_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

}
