/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PFeatureRectangle extends PSerialisationInterface {
  private long swigCPtr;

  protected PFeatureRectangle(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PFeatureRectangle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PFeatureRectangle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PFeatureRectangle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PFeatureRectangle() {
    this(PapillonCoreJavaJNI.new_PFeatureRectangle__SWIG_0(), true);
  }

  public PFeatureRectangle(PFeatureRectangle other) {
    this(PapillonCoreJavaJNI.new_PFeatureRectangle__SWIG_1(PFeatureRectangle.getCPtr(other), other), true);
  }

  public PFeatureRectangle(PRectanglef rectangle, PString description, float confidence) {
    this(PapillonCoreJavaJNI.new_PFeatureRectangle__SWIG_2(PRectanglef.getCPtr(rectangle), rectangle, PString.getCPtr(description), description, confidence), true);
  }

  public boolean IsValid() {
    return PapillonCoreJavaJNI.PFeatureRectangle_IsValid(swigCPtr, this);
  }

  public PRectanglef GetRectangle() {
    return new PRectanglef(PapillonCoreJavaJNI.PFeatureRectangle_GetRectangle(swigCPtr, this), true);
  }

  public PString GetDescription() {
    return new PString(PapillonCoreJavaJNI.PFeatureRectangle_GetDescription(swigCPtr, this), true);
  }

  public PString GetFeatureType() {
    return new PString(PapillonCoreJavaJNI.PFeatureRectangle_GetFeatureType(swigCPtr, this), true);
  }

  public float GetConfidence() {
    return PapillonCoreJavaJNI.PFeatureRectangle_GetConfidence(swigCPtr, this);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PFeatureRectangle_ToString(swigCPtr, this), true);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PFeatureRectangle_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PFeatureRectangle_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PFeatureRectangle_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PFeatureRectangle_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PFeatureRectangle_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

}
