/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PFrameToFrameTracker {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PFrameToFrameTracker(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PFrameToFrameTracker obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PFrameToFrameTracker(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static PResult Create(PProperties parameters, PFrameToFrameTracker detector) {
    return new PResult(PapillonCoreJavaJNI.PFrameToFrameTracker_Create__SWIG_0(PProperties.getCPtr(parameters), parameters, PFrameToFrameTracker.getCPtr(detector), detector), true);
  }

  public static PResult Create(PString parameters, PFrameToFrameTracker detector) {
    return new PResult(PapillonCoreJavaJNI.PFrameToFrameTracker_Create__SWIG_1(PString.getCPtr(parameters), parameters, PFrameToFrameTracker.getCPtr(detector), detector), true);
  }

  public PFrameToFrameTracker() {
    this(PapillonCoreJavaJNI.new_PFrameToFrameTracker__SWIG_0(), true);
  }

  public PFrameToFrameTracker(PFrameToFrameTracker other) {
    this(PapillonCoreJavaJNI.new_PFrameToFrameTracker__SWIG_1(PFrameToFrameTracker.getCPtr(other), other), true);
  }

  public PGuid GetId() {
    return new PGuid(PapillonCoreJavaJNI.PFrameToFrameTracker_GetId(swigCPtr, this), true);
  }

  public PString GetName() {
    return new PString(PapillonCoreJavaJNI.PFrameToFrameTracker_GetName(swigCPtr, this), true);
  }

  public PResult Apply(PFrame frame, PProperties parameters, PDetectionList io_detectionList) {
    return new PResult(PapillonCoreJavaJNI.PFrameToFrameTracker_Apply(swigCPtr, this, PFrame.getCPtr(frame), frame, PProperties.getCPtr(parameters), parameters, PDetectionList.getCPtr(io_detectionList), io_detectionList), true);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PFrameToFrameTracker_ToString(swigCPtr, this), true);
  }

  public void SetPimpl(SWIGTYPE_p_papillon__PFrameToFrameTrackerInterface pimpl) {
    PapillonCoreJavaJNI.PFrameToFrameTracker_SetPimpl(swigCPtr, this, SWIGTYPE_p_papillon__PFrameToFrameTrackerInterface.getCPtr(pimpl));
  }

}
