/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PGPSLocation extends PSerialisationInterface {
  private long swigCPtr;

  protected PGPSLocation(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PGPSLocation_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PGPSLocation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PGPSLocation(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PGPSLocation(double longitude, double latitude) {
    this(PapillonCoreJavaJNI.new_PGPSLocation__SWIG_0(longitude, latitude), true);
  }

  public PGPSLocation(double longitude) {
    this(PapillonCoreJavaJNI.new_PGPSLocation__SWIG_1(longitude), true);
  }

  public PGPSLocation() {
    this(PapillonCoreJavaJNI.new_PGPSLocation__SWIG_2(), true);
  }

  public PGPSLocation(PGPSLocation other) {
    this(PapillonCoreJavaJNI.new_PGPSLocation__SWIG_3(PGPSLocation.getCPtr(other), other), true);
  }

  public double GetLongitude() {
    return PapillonCoreJavaJNI.PGPSLocation_GetLongitude(swigCPtr, this);
  }

  public double GetLatitude() {
    return PapillonCoreJavaJNI.PGPSLocation_GetLatitude(swigCPtr, this);
  }

  public boolean IsValid() {
    return PapillonCoreJavaJNI.PGPSLocation_IsValid(swigCPtr, this);
  }

  public void Set(double longitude, double latitude) {
    PapillonCoreJavaJNI.PGPSLocation_Set(swigCPtr, this, longitude, latitude);
  }

  public void SetInvalid() {
    PapillonCoreJavaJNI.PGPSLocation_SetInvalid(swigCPtr, this);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PGPSLocation_ToString(swigCPtr, this), true);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PGPSLocation_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PGPSLocation_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PGPSLocation_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PGPSLocation_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PGPSLocation_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

}
