/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PGuid extends PSerialisationInterface {
  private long swigCPtr;

  protected PGuid(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PGuid_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PGuid obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PGuid(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PGuid() {
    this(PapillonCoreJavaJNI.new_PGuid__SWIG_0(), true);
  }

  public PGuid(PGuid other) {
    this(PapillonCoreJavaJNI.new_PGuid__SWIG_1(PGuid.getCPtr(other), other), true);
  }

  public PGuid(String str) {
    this(PapillonCoreJavaJNI.new_PGuid__SWIG_2(str), true);
  }

  public PGuid(PString str) {
    this(PapillonCoreJavaJNI.new_PGuid__SWIG_3(PString.getCPtr(str), str), true);
  }

  public PGuid(SWIGTYPE_p_unsigned_char buffer) {
    this(PapillonCoreJavaJNI.new_PGuid__SWIG_4(SWIGTYPE_p_unsigned_char.getCPtr(buffer)), true);
  }

  public PResult Set(String str) {
    return new PResult(PapillonCoreJavaJNI.PGuid_Set__SWIG_0(swigCPtr, this, str), true);
  }

  public void Set(SWIGTYPE_p_unsigned_char buffer) {
    PapillonCoreJavaJNI.PGuid_Set__SWIG_1(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(buffer));
  }

  public static PGuid CreateUniqueId() {
    return new PGuid(PapillonCoreJavaJNI.PGuid_CreateUniqueId(), true);
  }

  public boolean IsNull() {
    return PapillonCoreJavaJNI.PGuid_IsNull(swigCPtr, this);
  }

  public void SetNull() {
    PapillonCoreJavaJNI.PGuid_SetNull(swigCPtr, this);
  }

  public long GetHashCode() {
    return PapillonCoreJavaJNI.PGuid_GetHashCode(swigCPtr, this);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PGuid_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PGuid_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PGuid_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PGuid_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PGuid_ToString(swigCPtr, this), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PGuid_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

  public static PGuid getNULL_ID() {
    long cPtr = PapillonCoreJavaJNI.PGuid_NULL_ID_get();
    return (cPtr == 0) ? null : new PGuid(cPtr, false);
  }

}
