/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PIdentifyResults extends PSerialisationInterface {
  private long swigCPtr;

  protected PIdentifyResults(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PIdentifyResults_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PIdentifyResults obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PIdentifyResults(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PIdentifyResults() {
    this(PapillonCoreJavaJNI.new_PIdentifyResults__SWIG_0(), true);
  }

  public PIdentifyResults(PIdentifyResults other) {
    this(PapillonCoreJavaJNI.new_PIdentifyResults__SWIG_1(PIdentifyResults.getCPtr(other), other), true);
  }

  public PIdentifyResults Clone() {
    return new PIdentifyResults(PapillonCoreJavaJNI.PIdentifyResults_Clone(swigCPtr, this), true);
  }

  public void Clear() {
    PapillonCoreJavaJNI.PIdentifyResults_Clear(swigCPtr, this);
  }

  public boolean IsEmpty() {
    return PapillonCoreJavaJNI.PIdentifyResults_IsEmpty(swigCPtr, this);
  }

  public int Size() {
    return PapillonCoreJavaJNI.PIdentifyResults_Size(swigCPtr, this);
  }

  public void Add(PIdentifyResult r) {
    PapillonCoreJavaJNI.PIdentifyResults_Add(swigCPtr, this, PIdentifyResult.getCPtr(r), r);
  }

  public PIdentifyResult Get(int n) {
    return new PIdentifyResult(PapillonCoreJavaJNI.PIdentifyResults_Get(swigCPtr, this, n), true);
  }

  public double GetThreshold() {
    return PapillonCoreJavaJNI.PIdentifyResults_GetThreshold(swigCPtr, this);
  }

  public int GetNumberOfMatches() {
    return PapillonCoreJavaJNI.PIdentifyResults_GetNumberOfMatches(swigCPtr, this);
  }

  public PIdentifyResults GetResults() {
    return new PIdentifyResults(PapillonCoreJavaJNI.PIdentifyResults_GetResults(swigCPtr, this), true);
  }

  public void SetThreshold(double threshold) {
    PapillonCoreJavaJNI.PIdentifyResults_SetThreshold(swigCPtr, this, threshold);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PIdentifyResults_ToString(swigCPtr, this), true);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PIdentifyResults_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PIdentifyResults_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PIdentifyResults_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PIdentifyResults_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PIdentifyResults_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

}
