/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PInputVideoStream {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PInputVideoStream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PInputVideoStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PInputVideoStream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static PResult Open(PUri uri, PInputVideoStream inputVideoStream) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Open__SWIG_0(PUri.getCPtr(uri), uri, PInputVideoStream.getCPtr(inputVideoStream), inputVideoStream), true);
  }

  public static PResult Open(PString uri, PInputVideoStream inputVideoStream) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Open__SWIG_1(PString.getCPtr(uri), uri, PInputVideoStream.getCPtr(inputVideoStream), inputVideoStream), true);
  }

  public PInputVideoStream() {
    this(PapillonCoreJavaJNI.new_PInputVideoStream__SWIG_0(), true);
  }

  public PInputVideoStream(PInputVideoStream other) {
    this(PapillonCoreJavaJNI.new_PInputVideoStream__SWIG_1(PInputVideoStream.getCPtr(other), other), true);
  }

  public boolean IsOpened() {
    return PapillonCoreJavaJNI.PInputVideoStream_IsOpened(swigCPtr, this);
  }

  public PResult Release() {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Release(swigCPtr, this), true);
  }

  public PUri GetUri() {
    return new PUri(PapillonCoreJavaJNI.PInputVideoStream_GetUri(swigCPtr, this), true);
  }

  public PString GetReaderName() {
    return new PString(PapillonCoreJavaJNI.PInputVideoStream_GetReaderName(swigCPtr, this), true);
  }

  public EStreamStatus GetStatus(PString statusMessage) {
    return EStreamStatus.swigToEnum(PapillonCoreJavaJNI.PInputVideoStream_GetStatus__SWIG_0(swigCPtr, this, PString.getCPtr(statusMessage), statusMessage));
  }

  public EStreamStatus GetStatus() {
    return EStreamStatus.swigToEnum(PapillonCoreJavaJNI.PInputVideoStream_GetStatus__SWIG_1(swigCPtr, this));
  }

  public PResult GetFrame(PFrame frame, int timeOutMs) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_GetFrame__SWIG_0(swigCPtr, this, PFrame.getCPtr(frame), frame, timeOutMs), true);
  }

  public PResult GetFrame(PFrame frame) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_GetFrame__SWIG_1(swigCPtr, this, PFrame.getCPtr(frame), frame), true);
  }

  public PResult Get(PString propertyName, SWIGTYPE_p_int value) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Get__SWIG_0(swigCPtr, this, PString.getCPtr(propertyName), propertyName, SWIGTYPE_p_int.getCPtr(value)), true);
  }

  public PResult Get(PString propertyName, SWIGTYPE_p_double value) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Get__SWIG_1(swigCPtr, this, PString.getCPtr(propertyName), propertyName, SWIGTYPE_p_double.getCPtr(value)), true);
  }

  public PResult Get(PString propertyName, PGPSLocation location) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Get__SWIG_2(swigCPtr, this, PString.getCPtr(propertyName), propertyName, PGPSLocation.getCPtr(location), location), true);
  }

  public PResult Get(PString propertyName, PString str) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Get__SWIG_3(swigCPtr, this, PString.getCPtr(propertyName), propertyName, PString.getCPtr(str), str), true);
  }

  public PResult Get(PString propertyName, PRectanglef rectangle) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Get__SWIG_4(swigCPtr, this, PString.getCPtr(propertyName), propertyName, PRectanglef.getCPtr(rectangle), rectangle), true);
  }

  public PResult Get(PString propertyName, PByteArray byteArray) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Get__SWIG_5(swigCPtr, this, PString.getCPtr(propertyName), propertyName, PByteArray.getCPtr(byteArray), byteArray), true);
  }

  public PResult Get(PString propertyName, PImage image) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Get__SWIG_6(swigCPtr, this, PString.getCPtr(propertyName), propertyName, PImage.getCPtr(image), image), true);
  }

  public PResult Set(PString propertyName, int value) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Set__SWIG_0(swigCPtr, this, PString.getCPtr(propertyName), propertyName, value), true);
  }

  public PResult Set(PString propertyName, double value) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Set__SWIG_1(swigCPtr, this, PString.getCPtr(propertyName), propertyName, value), true);
  }

  public PResult Set(PString propertyName, PGPSLocation location) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Set__SWIG_2(swigCPtr, this, PString.getCPtr(propertyName), propertyName, PGPSLocation.getCPtr(location), location), true);
  }

  public PResult Set(PString propertyName, PString str) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Set__SWIG_3(swigCPtr, this, PString.getCPtr(propertyName), propertyName, PString.getCPtr(str), str), true);
  }

  public PResult Set(PString propertyName, PRectanglef rectangle) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Set__SWIG_4(swigCPtr, this, PString.getCPtr(propertyName), propertyName, PRectanglef.getCPtr(rectangle), rectangle), true);
  }

  public PResult Set(PString propertyName, PByteArray byteArray) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Set__SWIG_5(swigCPtr, this, PString.getCPtr(propertyName), propertyName, PByteArray.getCPtr(byteArray), byteArray), true);
  }

  public PResult Set(PString propertyName, PImage image) {
    return new PResult(PapillonCoreJavaJNI.PInputVideoStream_Set__SWIG_6(swigCPtr, this, PString.getCPtr(propertyName), propertyName, PImage.getCPtr(image), image), true);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PInputVideoStream_ToString(swigCPtr, this), true);
  }

  public void SetPimpl(SWIGTYPE_p_papillon__PInputVideoStreamInterface arg0) {
    PapillonCoreJavaJNI.PInputVideoStream_SetPimpl(swigCPtr, this, SWIGTYPE_p_papillon__PInputVideoStreamInterface.getCPtr(arg0));
  }

}
