/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PLogStream {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PLogStream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PLogStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PLogStream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PLogStream(PLog.ELogLevel logLevel, int lineNumber, PString filename) {
    this(PapillonCoreJavaJNI.new_PLogStream__SWIG_0(logLevel.swigValue(), lineNumber, PString.getCPtr(filename), filename), true);
  }

  public PLogStream(PLog.ELogLevel logLevel, int lineNumber) {
    this(PapillonCoreJavaJNI.new_PLogStream__SWIG_1(logLevel.swigValue(), lineNumber), true);
  }

  public PLogStream(PLog.ELogLevel logLevel) {
    this(PapillonCoreJavaJNI.new_PLogStream__SWIG_2(logLevel.swigValue()), true);
  }

  public PLog.ELogLevel GetLogLevel() {
    return PLog.ELogLevel.swigToEnum(PapillonCoreJavaJNI.PLogStream_GetLogLevel(swigCPtr, this));
  }

}
