/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class POutputStream {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected POutputStream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(POutputStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_POutputStream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public POutputStream() {
    this(PapillonCoreJavaJNI.new_POutputStream__SWIG_0(), true);
  }

  public POutputStream(POutputStream other) {
    this(PapillonCoreJavaJNI.new_POutputStream__SWIG_1(POutputStream.getCPtr(other), other), true);
  }

  public PResult IsOpened() {
    return new PResult(PapillonCoreJavaJNI.POutputStream_IsOpened(swigCPtr, this), true);
  }

  public PResult Close() {
    return new PResult(PapillonCoreJavaJNI.POutputStream_Close(swigCPtr, this), true);
  }

  public PResult WriteByte(int value) {
    return new PResult(PapillonCoreJavaJNI.POutputStream_WriteByte(swigCPtr, this, value), true);
  }

  public PResult WriteBytes(String values, int offset, int count) {
    return new PResult(PapillonCoreJavaJNI.POutputStream_WriteBytes__SWIG_0(swigCPtr, this, values, offset, count), true);
  }

  public PResult WriteBytes(PByteArray values, int count) {
    return new PResult(PapillonCoreJavaJNI.POutputStream_WriteBytes__SWIG_1(swigCPtr, this, PByteArray.getCPtr(values), values, count), true);
  }

  public PResult WriteBytes(PByteArray values) {
    return new PResult(PapillonCoreJavaJNI.POutputStream_WriteBytes__SWIG_2(swigCPtr, this, PByteArray.getCPtr(values), values), true);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.POutputStream_ToString(swigCPtr, this), true);
  }

}
