/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PPoint2Df extends PSerialisationInterface {
  private long swigCPtr;

  protected PPoint2Df(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PPoint2Df_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PPoint2Df obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PPoint2Df(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PPoint2Df(float x, float y) {
    this(PapillonCoreJavaJNI.new_PPoint2Df__SWIG_0(x, y), true);
  }

  public PPoint2Df(float x) {
    this(PapillonCoreJavaJNI.new_PPoint2Df__SWIG_1(x), true);
  }

  public PPoint2Df() {
    this(PapillonCoreJavaJNI.new_PPoint2Df__SWIG_2(), true);
  }

  public PPoint2Df(double x, double y) {
    this(PapillonCoreJavaJNI.new_PPoint2Df__SWIG_3(x, y), true);
  }

  public PPoint2Df(int x, int y) {
    this(PapillonCoreJavaJNI.new_PPoint2Df__SWIG_4(x, y), true);
  }

  public boolean IsValid() {
    return PapillonCoreJavaJNI.PPoint2Df_IsValid(swigCPtr, this);
  }

  public PPoint2Df Translated(float vx, float vy) {
    return new PPoint2Df(PapillonCoreJavaJNI.PPoint2Df_Translated(swigCPtr, this, vx, vy), true);
  }

  public PPoint2Di ToPPoint2Di() {
    return new PPoint2Di(PapillonCoreJavaJNI.PPoint2Df_ToPPoint2Di(swigCPtr, this), true);
  }

  public float EuclideanDistance(PPoint2Df other) {
    return PapillonCoreJavaJNI.PPoint2Df_EuclideanDistance(swigCPtr, this, PPoint2Df.getCPtr(other), other);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PPoint2Df_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PPoint2Df_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PPoint2Df_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PPoint2Df_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PPoint2Df_ToString(swigCPtr, this), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PPoint2Df_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

  public static PPoint2Df getC_BAD() {
    long cPtr = PapillonCoreJavaJNI.PPoint2Df_C_BAD_get();
    return (cPtr == 0) ? null : new PPoint2Df(cPtr, false);
  }

  public void setX(float value) {
    PapillonCoreJavaJNI.PPoint2Df_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return PapillonCoreJavaJNI.PPoint2Df_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    PapillonCoreJavaJNI.PPoint2Df_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return PapillonCoreJavaJNI.PPoint2Df_y_get(swigCPtr, this);
  }

}
