/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PPoint2DfList extends PSerialisationInterface {
  private long swigCPtr;

  protected PPoint2DfList(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PPoint2DfList_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PPoint2DfList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PPoint2DfList(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PPoint2DfList() {
    this(PapillonCoreJavaJNI.new_PPoint2DfList__SWIG_0(), true);
  }

  public PPoint2DfList(PPoint2DfList other) {
    this(PapillonCoreJavaJNI.new_PPoint2DfList__SWIG_1(PPoint2DfList.getCPtr(other), other), true);
  }

  public PPoint2DfList Clone() {
    return new PPoint2DfList(PapillonCoreJavaJNI.PPoint2DfList_Clone(swigCPtr, this), true);
  }

  public void Clear() {
    PapillonCoreJavaJNI.PPoint2DfList_Clear(swigCPtr, this);
  }

  public boolean IsEmpty() {
    return PapillonCoreJavaJNI.PPoint2DfList_IsEmpty(swigCPtr, this);
  }

  public int Size() {
    return PapillonCoreJavaJNI.PPoint2DfList_Size(swigCPtr, this);
  }

  public void Add(PPoint2Df p) {
    PapillonCoreJavaJNI.PPoint2DfList_Add(swigCPtr, this, PPoint2Df.getCPtr(p), p);
  }

  public PPoint2Df Get(int n) {
    return new PPoint2Df(PapillonCoreJavaJNI.PPoint2DfList_Get(swigCPtr, this, n), false);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PPoint2DfList_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PPoint2DfList_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PPoint2DfList_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PPoint2DfList_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PPoint2DfList_ToString(swigCPtr, this), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PPoint2DfList_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

}
