/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PPolygonf extends PSerialisationInterface {
  private long swigCPtr;

  protected PPolygonf(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PPolygonf_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PPolygonf obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PPolygonf(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PPolygonf(SWIGTYPE_p_std__vectorT_papillon__PPoint2Df_t points) {
    this(PapillonCoreJavaJNI.new_PPolygonf__SWIG_0(SWIGTYPE_p_std__vectorT_papillon__PPoint2Df_t.getCPtr(points)), true);
  }

  public PPolygonf() {
    this(PapillonCoreJavaJNI.new_PPolygonf__SWIG_1(), true);
  }

  public PPolygonf(PRectanglef r) {
    this(PapillonCoreJavaJNI.new_PPolygonf__SWIG_2(PRectanglef.getCPtr(r), r), true);
  }

  public PPolygonf(PPolygonf other) {
    this(PapillonCoreJavaJNI.new_PPolygonf__SWIG_3(PPolygonf.getCPtr(other), other), true);
  }

  public void Clear() {
    PapillonCoreJavaJNI.PPolygonf_Clear(swigCPtr, this);
  }

  public boolean IsEmpty() {
    return PapillonCoreJavaJNI.PPolygonf_IsEmpty(swigCPtr, this);
  }

  public int Size() {
    return PapillonCoreJavaJNI.PPolygonf_Size(swigCPtr, this);
  }

  public PPoint2Df GetPoint(int index) {
    return new PPoint2Df(PapillonCoreJavaJNI.PPolygonf_GetPoint(swigCPtr, this, index), true);
  }

  public PPoint2Df GetFirstPoint() {
    return new PPoint2Df(PapillonCoreJavaJNI.PPolygonf_GetFirstPoint(swigCPtr, this), true);
  }

  public PPoint2Df GetLastPoint() {
    return new PPoint2Df(PapillonCoreJavaJNI.PPolygonf_GetLastPoint(swigCPtr, this), true);
  }

  public PRectanglef GetBoundingRectangle() {
    return new PRectanglef(PapillonCoreJavaJNI.PPolygonf_GetBoundingRectangle(swigCPtr, this), true);
  }

  public PPolygonf GetConvexHull() {
    return new PPolygonf(PapillonCoreJavaJNI.PPolygonf_GetConvexHull(swigCPtr, this), true);
  }

  public void SetPoint(int index, PPoint2Df p) {
    PapillonCoreJavaJNI.PPolygonf_SetPoint(swigCPtr, this, index, PPoint2Df.getCPtr(p), p);
  }

  public PPolygonf AddPoint(float x, float y, int index) {
    return new PPolygonf(PapillonCoreJavaJNI.PPolygonf_AddPoint__SWIG_0(swigCPtr, this, x, y, index), false);
  }

  public PPolygonf AddPoint(float x, float y) {
    return new PPolygonf(PapillonCoreJavaJNI.PPolygonf_AddPoint__SWIG_1(swigCPtr, this, x, y), false);
  }

  public PPolygonf AddPoint(PPoint2Df p, int index) {
    return new PPolygonf(PapillonCoreJavaJNI.PPolygonf_AddPoint__SWIG_2(swigCPtr, this, PPoint2Df.getCPtr(p), p, index), false);
  }

  public PPolygonf AddPoint(PPoint2Df p) {
    return new PPolygonf(PapillonCoreJavaJNI.PPolygonf_AddPoint__SWIG_3(swigCPtr, this, PPoint2Df.getCPtr(p), p), false);
  }

  public PPolygonf Intersected(PPolygonf p) {
    return new PPolygonf(PapillonCoreJavaJNI.PPolygonf_Intersected(swigCPtr, this, PPolygonf.getCPtr(p), p), true);
  }

  public PPolygonf United(PPolygonf p) {
    return new PPolygonf(PapillonCoreJavaJNI.PPolygonf_United(swigCPtr, this, PPolygonf.getCPtr(p), p), true);
  }

  public PPolygonf Translated(PPoint2Df v) {
    return new PPolygonf(PapillonCoreJavaJNI.PPolygonf_Translated(swigCPtr, this, PPoint2Df.getCPtr(v), v), true);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PPolygonf_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PPolygonf_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PPolygonf_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PPolygonf_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PPolygonf_ToString(swigCPtr, this), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PPolygonf_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

}
