/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PRectanglef extends PSerialisationInterface {
  private long swigCPtr;

  protected PRectanglef(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PRectanglef_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PRectanglef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PRectanglef(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PRectanglef(float x, float y, float w, float h) {
    this(PapillonCoreJavaJNI.new_PRectanglef__SWIG_0(x, y, w, h), true);
  }

  public PRectanglef(float x, float y, float w) {
    this(PapillonCoreJavaJNI.new_PRectanglef__SWIG_1(x, y, w), true);
  }

  public PRectanglef(float x, float y) {
    this(PapillonCoreJavaJNI.new_PRectanglef__SWIG_2(x, y), true);
  }

  public PRectanglef(float x) {
    this(PapillonCoreJavaJNI.new_PRectanglef__SWIG_3(x), true);
  }

  public PRectanglef() {
    this(PapillonCoreJavaJNI.new_PRectanglef__SWIG_4(), true);
  }

  public boolean IsValid() {
    return PapillonCoreJavaJNI.PRectanglef_IsValid(swigCPtr, this);
  }

  public float GetWidth() {
    return PapillonCoreJavaJNI.PRectanglef_GetWidth(swigCPtr, this);
  }

  public float GetHeight() {
    return PapillonCoreJavaJNI.PRectanglef_GetHeight(swigCPtr, this);
  }

  public PPoint2Df GetCentre() {
    return new PPoint2Df(PapillonCoreJavaJNI.PRectanglef_GetCentre(swigCPtr, this), true);
  }

  public PSizef GetSize() {
    return new PSizef(PapillonCoreJavaJNI.PRectanglef_GetSize(swigCPtr, this), true);
  }

  public float GetArea() {
    return PapillonCoreJavaJNI.PRectanglef_GetArea(swigCPtr, this);
  }

  public float GetOverlapArea(PRectanglef i_rectangle) {
    return PapillonCoreJavaJNI.PRectanglef_GetOverlapArea(swigCPtr, this, PRectanglef.getCPtr(i_rectangle), i_rectangle);
  }

  public float GetDiceCoefficient(PRectanglef i_rectangle) {
    return PapillonCoreJavaJNI.PRectanglef_GetDiceCoefficient(swigCPtr, this, PRectanglef.getCPtr(i_rectangle), i_rectangle);
  }

  public boolean Contains(PPoint2Df p) {
    return PapillonCoreJavaJNI.PRectanglef_Contains(swigCPtr, this, PPoint2Df.getCPtr(p), p);
  }

  public PRectanglef Expand(float expandBy) {
    return new PRectanglef(PapillonCoreJavaJNI.PRectanglef_Expand(swigCPtr, this, expandBy), true);
  }

  public PRectanglei ToPRectanglei() {
    return new PRectanglei(PapillonCoreJavaJNI.PRectanglef_ToPRectanglei(swigCPtr, this), true);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PRectanglef_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PRectanglef_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PRectanglef_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PRectanglef_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PRectanglef_ToString(swigCPtr, this), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PRectanglef_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

  public static PRectanglef getC_BAD() {
    long cPtr = PapillonCoreJavaJNI.PRectanglef_C_BAD_get();
    return (cPtr == 0) ? null : new PRectanglef(cPtr, false);
  }

  public void setX(float value) {
    PapillonCoreJavaJNI.PRectanglef_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return PapillonCoreJavaJNI.PRectanglef_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    PapillonCoreJavaJNI.PRectanglef_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return PapillonCoreJavaJNI.PRectanglef_y_get(swigCPtr, this);
  }

  public void setW(float value) {
    PapillonCoreJavaJNI.PRectanglef_w_set(swigCPtr, this, value);
  }

  public float getW() {
    return PapillonCoreJavaJNI.PRectanglef_w_get(swigCPtr, this);
  }

  public void setH(float value) {
    PapillonCoreJavaJNI.PRectanglef_h_set(swigCPtr, this, value);
  }

  public float getH() {
    return PapillonCoreJavaJNI.PRectanglef_h_get(swigCPtr, this);
  }

}
