/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PSizef extends PSerialisationInterface {
  private long swigCPtr;

  protected PSizef(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PSizef_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PSizef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PSizef(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PSizef() {
    this(PapillonCoreJavaJNI.new_PSizef__SWIG_0(), true);
  }

  public PSizef(float width, float height) {
    this(PapillonCoreJavaJNI.new_PSizef__SWIG_1(width, height), true);
  }

  public PSizef(PSizef other) {
    this(PapillonCoreJavaJNI.new_PSizef__SWIG_2(PSizef.getCPtr(other), other), true);
  }

  public boolean IsValid() {
    return PapillonCoreJavaJNI.PSizef_IsValid(swigCPtr, this);
  }

  public float GetWidth() {
    return PapillonCoreJavaJNI.PSizef_GetWidth(swigCPtr, this);
  }

  public float GetHeight() {
    return PapillonCoreJavaJNI.PSizef_GetHeight(swigCPtr, this);
  }

  public void Set(float width, float height) {
    PapillonCoreJavaJNI.PSizef_Set(swigCPtr, this, width, height);
  }

  public void SetWidth(float width) {
    PapillonCoreJavaJNI.PSizef_SetWidth(swigCPtr, this, width);
  }

  public void SetHeight(float height) {
    PapillonCoreJavaJNI.PSizef_SetHeight(swigCPtr, this, height);
  }

  public PSizef Scale(float factor) {
    return new PSizef(PapillonCoreJavaJNI.PSizef_Scale(swigCPtr, this, factor), true);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PSizef_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PSizef_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PSizef_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PSizef_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PSizef_ToString(swigCPtr, this), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PSizef_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

  public static PSizef getC_ZERO() {
    long cPtr = PapillonCoreJavaJNI.PSizef_C_ZERO_get();
    return (cPtr == 0) ? null : new PSizef(cPtr, false);
  }

}
