/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PStdOutputStream extends POutputStream {
  private long swigCPtr;

  protected PStdOutputStream(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PStdOutputStream_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PStdOutputStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PStdOutputStream(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PStdOutputStream(SWIGTYPE_p_std__ostream os, boolean delegateMemoryManagement) {
    this(PapillonCoreJavaJNI.new_PStdOutputStream__SWIG_0(SWIGTYPE_p_std__ostream.getCPtr(os), delegateMemoryManagement), true);
  }

  public PStdOutputStream(SWIGTYPE_p_std__ostream os) {
    this(PapillonCoreJavaJNI.new_PStdOutputStream__SWIG_1(SWIGTYPE_p_std__ostream.getCPtr(os)), true);
  }

  public SWIGTYPE_p_std__ostream GetStdOStream() {
    long cPtr = PapillonCoreJavaJNI.PStdOutputStream_GetStdOStream(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__ostream(cPtr, false);
  }

}
