/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PString extends PSerialisationInterface {
  private long swigCPtr;

  protected PString(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PString_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PString(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PString() {
    this(PapillonCoreJavaJNI.new_PString__SWIG_0(), true);
  }

  public PString(PString other) {
    this(PapillonCoreJavaJNI.new_PString__SWIG_1(PString.getCPtr(other), other), true);
  }

  public PString(String str) {
    this(PapillonCoreJavaJNI.new_PString__SWIG_2(str), true);
  }

  public PString(SWIGTYPE_p_wchar_t str) {
    this(PapillonCoreJavaJNI.new_PString__SWIG_3(SWIGTYPE_p_wchar_t.getCPtr(str)), true);
  }

  public PString(String str) {
    this(PapillonCoreJavaJNI.new_PString__SWIG_5(str), true);
  }

  public PString(char c) {
    this(PapillonCoreJavaJNI.new_PString__SWIG_6(c), true);
  }

  public PString(int c) {
    this(PapillonCoreJavaJNI.new_PString__SWIG_7(c), true);
  }

  public PString(long n) {
    this(PapillonCoreJavaJNI.new_PString__SWIG_9(n), true);
  }

  public PString(java.math.BigInteger n) {
    this(PapillonCoreJavaJNI.new_PString__SWIG_11(n), true);
  }

  public PString(double n, char format, int precision) {
    this(PapillonCoreJavaJNI.new_PString__SWIG_12(n, format, precision), true);
  }

  public PString(double n, char format) {
    this(PapillonCoreJavaJNI.new_PString__SWIG_13(n, format), true);
  }

  public PString(double n) {
    this(PapillonCoreJavaJNI.new_PString__SWIG_14(n), true);
  }

  public int At(int position) {
    return PapillonCoreJavaJNI.PString_At(swigCPtr, this, position);
  }

  public boolean IsEmpty() {
    return PapillonCoreJavaJNI.PString_IsEmpty(swigCPtr, this);
  }

  public boolean StartsWith(PString s) {
    return PapillonCoreJavaJNI.PString_StartsWith(swigCPtr, this, PString.getCPtr(s), s);
  }

  public boolean EndsWith(PString s) {
    return PapillonCoreJavaJNI.PString_EndsWith(swigCPtr, this, PString.getCPtr(s), s);
  }

  public boolean Contains(PString s) {
    return PapillonCoreJavaJNI.PString_Contains(swigCPtr, this, PString.getCPtr(s), s);
  }

  public int Size() {
    return PapillonCoreJavaJNI.PString_Size(swigCPtr, this);
  }

  public String c_str() {
    return PapillonCoreJavaJNI.PString_c_str(swigCPtr, this);
  }

  public String ConstUTF8() {
    return PapillonCoreJavaJNI.PString_ConstUTF8(swigCPtr, this);
  }

  public SWIGTYPE_p_unsigned_short ConstUTF16() {
    long cPtr = PapillonCoreJavaJNI.PString_ConstUTF16(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public int ToWCharArray(SWIGTYPE_p_wchar_t array) {
    return PapillonCoreJavaJNI.PString_ToWCharArray(swigCPtr, this, SWIGTYPE_p_wchar_t.getCPtr(array));
  }

  public PByteArray ToUTF8() {
    return new PByteArray(PapillonCoreJavaJNI.PString_ToUTF8(swigCPtr, this), true);
  }

  public PString Substring(int position, int n) {
    return new PString(PapillonCoreJavaJNI.PString_Substring__SWIG_0(swigCPtr, this, position, n), true);
  }

  public PString Substring(int position) {
    return new PString(PapillonCoreJavaJNI.PString_Substring__SWIG_1(swigCPtr, this, position), true);
  }

  public void Chop(int n) {
    PapillonCoreJavaJNI.PString_Chop(swigCPtr, this, n);
  }

  public PString ToUpper() {
    return new PString(PapillonCoreJavaJNI.PString_ToUpper(swigCPtr, this), true);
  }

  public PStringList Split(int separator) {
    return new PStringList(PapillonCoreJavaJNI.PString_Split(swigCPtr, this, separator), true);
  }

  public PString Arg(PString str, int fieldWidth, int fillChar) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_0(swigCPtr, this, PString.getCPtr(str), str, fieldWidth, fillChar), true);
  }

  public PString Arg(PString str, int fieldWidth) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_1(swigCPtr, this, PString.getCPtr(str), str, fieldWidth), true);
  }

  public PString Arg(PString str) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_2(swigCPtr, this, PString.getCPtr(str), str), true);
  }

  public PString Arg(String value) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_3(swigCPtr, this, value), true);
  }

  public PString Arg(int value, int fieldWidth, int base, int fillChar) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_4(swigCPtr, this, value, fieldWidth, base, fillChar), true);
  }

  public PString Arg(int value, int fieldWidth, int base) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_5(swigCPtr, this, value, fieldWidth, base), true);
  }

  public PString Arg(int value, int fieldWidth) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_6(swigCPtr, this, value, fieldWidth), true);
  }

  public PString Arg(int value) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_7(swigCPtr, this, value), true);
  }

  public PString Arg(long value, int fieldWidth, int base, int fillChar) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_8(swigCPtr, this, value, fieldWidth, base, fillChar), true);
  }

  public PString Arg(long value, int fieldWidth, int base) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_9(swigCPtr, this, value, fieldWidth, base), true);
  }

  public PString Arg(long value, int fieldWidth) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_10(swigCPtr, this, value, fieldWidth), true);
  }

  public PString Arg(long value) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_11(swigCPtr, this, value), true);
  }

  public PString Arg(java.math.BigInteger value, int fieldWidth, int base, int fillChar) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_16(swigCPtr, this, value, fieldWidth, base, fillChar), true);
  }

  public PString Arg(java.math.BigInteger value, int fieldWidth, int base) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_17(swigCPtr, this, value, fieldWidth, base), true);
  }

  public PString Arg(java.math.BigInteger value, int fieldWidth) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_18(swigCPtr, this, value, fieldWidth), true);
  }

  public PString Arg(java.math.BigInteger value) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_19(swigCPtr, this, value), true);
  }

  public PString Arg(double value, int fieldWidth, char format, int precision, int fillChar) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_20(swigCPtr, this, value, fieldWidth, format, precision, fillChar), true);
  }

  public PString Arg(double value, int fieldWidth, char format, int precision) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_21(swigCPtr, this, value, fieldWidth, format, precision), true);
  }

  public PString Arg(double value, int fieldWidth, char format) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_22(swigCPtr, this, value, fieldWidth, format), true);
  }

  public PString Arg(double value, int fieldWidth) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_23(swigCPtr, this, value, fieldWidth), true);
  }

  public PString Arg(double value) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_24(swigCPtr, this, value), true);
  }

  public PString Arg(float value, int fieldWidth, char format, int precision, int fillChar) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_25(swigCPtr, this, value, fieldWidth, format, precision, fillChar), true);
  }

  public PString Arg(float value, int fieldWidth, char format, int precision) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_26(swigCPtr, this, value, fieldWidth, format, precision), true);
  }

  public PString Arg(float value, int fieldWidth, char format) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_27(swigCPtr, this, value, fieldWidth, format), true);
  }

  public PString Arg(float value, int fieldWidth) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_28(swigCPtr, this, value, fieldWidth), true);
  }

  public PString Arg(float value) {
    return new PString(PapillonCoreJavaJNI.PString_Arg__SWIG_29(swigCPtr, this, value), true);
  }

  public int Compare(PString other) {
    return PapillonCoreJavaJNI.PString_Compare(swigCPtr, this, PString.getCPtr(other), other);
  }

  public int ToInt32(SWIGTYPE_p_bool ok) {
    return PapillonCoreJavaJNI.PString_ToInt32__SWIG_0(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(ok));
  }

  public int ToInt32() {
    return PapillonCoreJavaJNI.PString_ToInt32__SWIG_1(swigCPtr, this);
  }

  public long ToInt64(SWIGTYPE_p_bool ok) {
    return PapillonCoreJavaJNI.PString_ToInt64__SWIG_0(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(ok));
  }

  public long ToInt64() {
    return PapillonCoreJavaJNI.PString_ToInt64__SWIG_1(swigCPtr, this);
  }

  public double ToDouble(SWIGTYPE_p_bool ok) {
    return PapillonCoreJavaJNI.PString_ToDouble__SWIG_0(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(ok));
  }

  public double ToDouble() {
    return PapillonCoreJavaJNI.PString_ToDouble__SWIG_1(swigCPtr, this);
  }

  public long GetHashCode() {
    return PapillonCoreJavaJNI.PString_GetHashCode(swigCPtr, this);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PString_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PString_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PString_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PString_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PString_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

}
