/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PStringList extends PSerialisationInterface {
  private long swigCPtr;

  protected PStringList(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PStringList_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PStringList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PStringList(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PStringList() {
    this(PapillonCoreJavaJNI.new_PStringList__SWIG_0(), true);
  }

  public PStringList(PStringList other) {
    this(PapillonCoreJavaJNI.new_PStringList__SWIG_1(PStringList.getCPtr(other), other), true);
  }

  public void Clear() {
    PapillonCoreJavaJNI.PStringList_Clear(swigCPtr, this);
  }

  public boolean IsEmpty() {
    return PapillonCoreJavaJNI.PStringList_IsEmpty(swigCPtr, this);
  }

  public int Size() {
    return PapillonCoreJavaJNI.PStringList_Size(swigCPtr, this);
  }

  public PString Get(int index) {
    return new PString(PapillonCoreJavaJNI.PStringList_Get(swigCPtr, this, index), true);
  }

  public PStringList Add(PString s) {
    return new PStringList(PapillonCoreJavaJNI.PStringList_Add(swigCPtr, this, PString.getCPtr(s), s), false);
  }

  public boolean Contains(PString s) {
    return PapillonCoreJavaJNI.PStringList_Contains(swigCPtr, this, PString.getCPtr(s), s);
  }

  public PString Join(PString separator) {
    return new PString(PapillonCoreJavaJNI.PStringList_Join(swigCPtr, this, PString.getCPtr(separator), separator), true);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PStringList_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PStringList_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PStringList_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PStringList_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PStringList_ToString(swigCPtr, this), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PStringList_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

}
