/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PTextFile {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PTextFile(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PTextFile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PTextFile(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static PResult Create(PString filename, PTextFile textFile) {
    return new PResult(PapillonCoreJavaJNI.PTextFile_Create(PString.getCPtr(filename), filename, PTextFile.getCPtr(textFile), textFile), true);
  }

  public PTextFile() {
    this(PapillonCoreJavaJNI.new_PTextFile__SWIG_0(), true);
  }

  public PTextFile(PTextFile other) {
    this(PapillonCoreJavaJNI.new_PTextFile__SWIG_1(PTextFile.getCPtr(other), other), true);
  }

  public PString GetFileName() {
    return new PString(PapillonCoreJavaJNI.PTextFile_GetFileName(swigCPtr, this), false);
  }

  public int GetNumberOfLines() {
    return PapillonCoreJavaJNI.PTextFile_GetNumberOfLines(swigCPtr, this);
  }

  public PString GetLine(int lineNumber) {
    return new PString(PapillonCoreJavaJNI.PTextFile_GetLine__SWIG_0(swigCPtr, this, lineNumber), true);
  }

  public PStringList GetLine(int lineNumber, PString separators) {
    return new PStringList(PapillonCoreJavaJNI.PTextFile_GetLine__SWIG_1(swigCPtr, this, lineNumber, PString.getCPtr(separators), separators), true);
  }

  public PStringList GetLines() {
    return new PStringList(PapillonCoreJavaJNI.PTextFile_GetLines(swigCPtr, this), false);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PTextFile_ToString(swigCPtr, this), true);
  }

}
