/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PTime extends PSerialisationInterface {
  private long swigCPtr;

  protected PTime(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PTime_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PTime obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PTime(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PTime(int h, int m, int s, int ms) {
    this(PapillonCoreJavaJNI.new_PTime__SWIG_0(h, m, s, ms), true);
  }

  public PTime(int h, int m, int s) {
    this(PapillonCoreJavaJNI.new_PTime__SWIG_1(h, m, s), true);
  }

  public PTime(int h, int m) {
    this(PapillonCoreJavaJNI.new_PTime__SWIG_2(h, m), true);
  }

  public PTime(int h) {
    this(PapillonCoreJavaJNI.new_PTime__SWIG_3(h), true);
  }

  public PTime() {
    this(PapillonCoreJavaJNI.new_PTime__SWIG_4(), true);
  }

  public PTime(PTime other) {
    this(PapillonCoreJavaJNI.new_PTime__SWIG_5(PTime.getCPtr(other), other), true);
  }

  public PTime(PString str, PString format) {
    this(PapillonCoreJavaJNI.new_PTime__SWIG_6(PString.getCPtr(str), str, PString.getCPtr(format), format), true);
  }

  public PTime(PString str) {
    this(PapillonCoreJavaJNI.new_PTime__SWIG_7(PString.getCPtr(str), str), true);
  }

  public static PTime Current() {
    return new PTime(PapillonCoreJavaJNI.PTime_Current(), true);
  }

  public int GetHour() {
    return PapillonCoreJavaJNI.PTime_GetHour(swigCPtr, this);
  }

  public int GetMinute() {
    return PapillonCoreJavaJNI.PTime_GetMinute(swigCPtr, this);
  }

  public int GetSecond() {
    return PapillonCoreJavaJNI.PTime_GetSecond(swigCPtr, this);
  }

  public int GetMillisecond() {
    return PapillonCoreJavaJNI.PTime_GetMillisecond(swigCPtr, this);
  }

  public boolean IsValid() {
    return PapillonCoreJavaJNI.PTime_IsValid(swigCPtr, this);
  }

  public boolean SetTime(int h, int m, int s, int ms) {
    return PapillonCoreJavaJNI.PTime_SetTime__SWIG_0(swigCPtr, this, h, m, s, ms);
  }

  public boolean SetTime(int h, int m, int s) {
    return PapillonCoreJavaJNI.PTime_SetTime__SWIG_1(swigCPtr, this, h, m, s);
  }

  public PTime AddMillisecond(int n) {
    return new PTime(PapillonCoreJavaJNI.PTime_AddMillisecond(swigCPtr, this, n), true);
  }

  public int GetMillisecondsTo(PTime t) {
    return PapillonCoreJavaJNI.PTime_GetMillisecondsTo(swigCPtr, this, PTime.getCPtr(t), t);
  }

  public int Compare(PTime other) {
    return PapillonCoreJavaJNI.PTime_Compare(swigCPtr, this, PTime.getCPtr(other), other);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PTime_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PTime_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PTime_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PTime_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public PString ToString(PString format) {
    return new PString(PapillonCoreJavaJNI.PTime_ToString__SWIG_0(swigCPtr, this, PString.getCPtr(format), format), true);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PTime_ToString__SWIG_1(swigCPtr, this), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PTime_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

}
