/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PTrack extends PSerialisationInterface {
  private long swigCPtr;

  protected PTrack(long cPtr, boolean cMemoryOwn) {
    super(PapillonCoreJavaJNI.PTrack_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PTrack obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PapillonCoreJavaJNI.delete_PTrack(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PTrack() {
    this(PapillonCoreJavaJNI.new_PTrack__SWIG_0(), true);
  }

  public PTrack(PGuid id, float confidence) {
    this(PapillonCoreJavaJNI.new_PTrack__SWIG_1(PGuid.getCPtr(id), id, confidence), true);
  }

  public PTrack(PTrack other) {
    this(PapillonCoreJavaJNI.new_PTrack__SWIG_2(PTrack.getCPtr(other), other), true);
  }

  public PTrack Clone() {
    return new PTrack(PapillonCoreJavaJNI.PTrack_Clone(swigCPtr, this), true);
  }

  public PGuid GetTrackId() {
    return new PGuid(PapillonCoreJavaJNI.PTrack_GetTrackId(swigCPtr, this), true);
  }

  public float GetConfidence() {
    return PapillonCoreJavaJNI.PTrack_GetConfidence(swigCPtr, this);
  }

  public void SetTrackId(PGuid val) {
    PapillonCoreJavaJNI.PTrack_SetTrackId(swigCPtr, this, PGuid.getCPtr(val), val);
  }

  public void SetConfidence(float val) {
    PapillonCoreJavaJNI.PTrack_SetConfidence(swigCPtr, this, val);
  }

  public void Clear() {
    PapillonCoreJavaJNI.PTrack_Clear(swigCPtr, this);
  }

  public PResult Write(POutputStream os, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PTrack_Write__SWIG_0(swigCPtr, this, POutputStream.getCPtr(os), os, format.swigValue()), true);
  }

  public PResult Write(POutputStream os) {
    return new PResult(PapillonCoreJavaJNI.PTrack_Write__SWIG_1(swigCPtr, this, POutputStream.getCPtr(os), os), true);
  }

  public PResult Read(PInputStream is, ESerialisationFormat format) {
    return new PResult(PapillonCoreJavaJNI.PTrack_Read__SWIG_0(swigCPtr, this, PInputStream.getCPtr(is), is, format.swigValue()), true);
  }

  public PResult Read(PInputStream is) {
    return new PResult(PapillonCoreJavaJNI.PTrack_Read__SWIG_1(swigCPtr, this, PInputStream.getCPtr(is), is), true);
  }

  public PString ToString() {
    return new PString(PapillonCoreJavaJNI.PTrack_ToString(swigCPtr, this), true);
  }

  public static PClassId getC_CLASSID() {
    long cPtr = PapillonCoreJavaJNI.PTrack_C_CLASSID_get();
    return (cPtr == 0) ? null : new PClassId(cPtr, false);
  }

}
