//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum EVerificationSecurityLevel {
  E_VERIFICATION_SECURITY_LEVEL_MANUAL,
  E_VERIFICATION_SECURITY_LEVEL_LOW,
  E_VERIFICATION_SECURITY_LEVEL_MEDIUM,
  E_VERIFICATION_SECURITY_LEVEL_HIGH
}
