//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PAnalytics : PPluginInstance {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PAnalytics(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PapillonPINVOKE.PAnalytics_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PAnalytics obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PAnalytics() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PapillonPINVOKE.delete_PAnalytics(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static PResult Create(string productName, PProperties parameters, PAnalytics analytics) {
    PResult ret = new PResult(PapillonPINVOKE.PAnalytics_Create__SWIG_0(productName, PProperties.getCPtr(parameters), PAnalytics.getCPtr(analytics)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static PResult Create(SWIGTYPE_p_papillon__PPlugin plugin, PProperties parameters, PAnalytics analytics) {
    PResult ret = new PResult(PapillonPINVOKE.PAnalytics_Create__SWIG_1(SWIGTYPE_p_papillon__PPlugin.getCPtr(plugin), PProperties.getCPtr(parameters), PAnalytics.getCPtr(analytics)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PAnalytics() : this(PapillonPINVOKE.new_PAnalytics__SWIG_0(), true) {
  }

  public PAnalytics(PAnalytics other) : this(PapillonPINVOKE.new_PAnalytics__SWIG_1(PAnalytics.getCPtr(other)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public PResult Apply(PFrame frame, PList events) {
    PResult ret = new PResult(PapillonPINVOKE.PAnalytics_Apply(swigCPtr, PFrame.getCPtr(frame), PList.getCPtr(events)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PResult Finish(PList events) {
    PResult ret = new PResult(PapillonPINVOKE.PAnalytics_Finish(swigCPtr, PList.getCPtr(events)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PSizei GetMinimumInputResolution() {
    PSizei ret = new PSizei(PapillonPINVOKE.PAnalytics_GetMinimumInputResolution(swigCPtr), true);
    return ret;
  }

  public PResult DrawOSD(PImage image) {
    PResult ret = new PResult(PapillonPINVOKE.PAnalytics_DrawOSD(swigCPtr, PImage.getCPtr(image)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
