//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PDatabaseStore : PStore {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PDatabaseStore(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PapillonPINVOKE.PDatabaseStore_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PDatabaseStore obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PDatabaseStore() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PapillonPINVOKE.delete_PDatabaseStore(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static PResult Open(string dbName, PStore store) {
    PResult ret = new PResult(PapillonPINVOKE.PDatabaseStore_Open__SWIG_0(dbName, PStore.getCPtr(store)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static PResult Open(string dbHost, int dbPort, string dbName, string username, string password, PStore store) {
    PResult ret = new PResult(PapillonPINVOKE.PDatabaseStore_Open__SWIG_1(dbHost, dbPort, dbName, username, password, PStore.getCPtr(store)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PDatabaseStore(PDatabaseStore other) : this(PapillonPINVOKE.new_PDatabaseStore(PDatabaseStore.getCPtr(other)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public PSqlDatabase GetDatabase() {
    PSqlDatabase ret = new PSqlDatabase(PapillonPINVOKE.PDatabaseStore_GetDatabase(swigCPtr), true);
    return ret;
  }

}
