//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PDouble : PObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PDouble(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PapillonPINVOKE.PDouble_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PDouble obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PDouble() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PapillonPINVOKE.delete_PDouble(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public PDouble(double value) : this(PapillonPINVOKE.new_PDouble__SWIG_0(value), true) {
  }

  public PDouble() : this(PapillonPINVOKE.new_PDouble__SWIG_1(), true) {
  }

  public PDouble(PDouble other) : this(PapillonPINVOKE.new_PDouble__SWIG_2(PDouble.getCPtr(other)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public double GetValue() {
    double ret = PapillonPINVOKE.PDouble_GetValue(swigCPtr);
    return ret;
  }

}
