//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PIdentifyResult : PObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PIdentifyResult(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PapillonPINVOKE.PIdentifyResult_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PIdentifyResult obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PIdentifyResult() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PapillonPINVOKE.delete_PIdentifyResult(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public PIdentifyResult() : this(PapillonPINVOKE.new_PIdentifyResult__SWIG_0(), true) {
  }

  public PIdentifyResult(PGuid identityId, string name, int rank, double score) : this(PapillonPINVOKE.new_PIdentifyResult__SWIG_1(PGuid.getCPtr(identityId), name, rank, score), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public PIdentifyResult(PIdentifyResult other) : this(PapillonPINVOKE.new_PIdentifyResult__SWIG_2(PIdentifyResult.getCPtr(other)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public PIdentifyResult Clone() {
    PIdentifyResult ret = new PIdentifyResult(PapillonPINVOKE.PIdentifyResult_Clone(swigCPtr), true);
    return ret;
  }

  public void Reset() {
    PapillonPINVOKE.PIdentifyResult_Reset(swigCPtr);
  }

  public bool IsEmpty() {
    bool ret = PapillonPINVOKE.PIdentifyResult_IsEmpty(swigCPtr);
    return ret;
  }

  public PGuid GetIdentityId() {
    PGuid ret = new PGuid(PapillonPINVOKE.PIdentifyResult_GetIdentityId(swigCPtr), false);
    return ret;
  }

  public string GetName() {
    string ret = PapillonPINVOKE.PIdentifyResult_GetName(swigCPtr);
    return ret;
  }

  public int GetRank() {
    int ret = PapillonPINVOKE.PIdentifyResult_GetRank(swigCPtr);
    return ret;
  }

  public double GetScore() {
    double ret = PapillonPINVOKE.PIdentifyResult_GetScore(swigCPtr);
    return ret;
  }

}
