//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PInt32 : PObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PInt32(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PapillonPINVOKE.PInt32_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PInt32 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PInt32() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PapillonPINVOKE.delete_PInt32(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public PInt32(int value) : this(PapillonPINVOKE.new_PInt32__SWIG_0(value), true) {
  }

  public PInt32() : this(PapillonPINVOKE.new_PInt32__SWIG_1(), true) {
  }

  public PInt32(PInt32 other) : this(PapillonPINVOKE.new_PInt32__SWIG_2(PInt32.getCPtr(other)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public int GetValue() {
    int ret = PapillonPINVOKE.PInt32_GetValue(swigCPtr);
    return ret;
  }

}
