//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PMatchScore : PObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PMatchScore(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PapillonPINVOKE.PMatchScore_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PMatchScore obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PMatchScore() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PapillonPINVOKE.delete_PMatchScore(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public PMatchScore() : this(PapillonPINVOKE.new_PMatchScore__SWIG_0(), true) {
  }

  public PMatchScore(PGuid objectId1, PGuid objectId2, double score, double threshold) : this(PapillonPINVOKE.new_PMatchScore__SWIG_1(PGuid.getCPtr(objectId1), PGuid.getCPtr(objectId2), score, threshold), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public PMatchScore(PGuid objectId1, PGuid objectId2, double score) : this(PapillonPINVOKE.new_PMatchScore__SWIG_2(PGuid.getCPtr(objectId1), PGuid.getCPtr(objectId2), score), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public PMatchScore(PMatchScore other) : this(PapillonPINVOKE.new_PMatchScore__SWIG_3(PMatchScore.getCPtr(other)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reset() {
    PapillonPINVOKE.PMatchScore_Reset(swigCPtr);
  }

  public void SetScore(double score) {
    PapillonPINVOKE.PMatchScore_SetScore(swigCPtr, score);
  }

  public double GetScore() {
    double ret = PapillonPINVOKE.PMatchScore_GetScore(swigCPtr);
    return ret;
  }

  public void SetThreshold(double threshold) {
    PapillonPINVOKE.PMatchScore_SetThreshold(swigCPtr, threshold);
  }

  public double GetThreshold() {
    double ret = PapillonPINVOKE.PMatchScore_GetThreshold(swigCPtr);
    return ret;
  }

  public bool IsVerified() {
    bool ret = PapillonPINVOKE.PMatchScore_IsVerified(swigCPtr);
    return ret;
  }

  public PGuid GetIdentityId1() {
    PGuid ret = new PGuid(PapillonPINVOKE.PMatchScore_GetIdentityId1(swigCPtr), true);
    return ret;
  }

  public PGuid GetIdentityId2() {
    PGuid ret = new PGuid(PapillonPINVOKE.PMatchScore_GetIdentityId2(swigCPtr), true);
    return ret;
  }

}
