//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PMemoryStream : PByteStream {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PMemoryStream(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PapillonPINVOKE.PMemoryStream_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PMemoryStream obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PMemoryStream() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PapillonPINVOKE.delete_PMemoryStream(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public PMemoryStream() : this(PapillonPINVOKE.new_PMemoryStream__SWIG_0(), true) {
  }

  public PMemoryStream(string data, int n) : this(PapillonPINVOKE.new_PMemoryStream__SWIG_1(data, n), true) {
  }

  public PMemoryStream(PByteArray buffer) : this(PapillonPINVOKE.new_PMemoryStream__SWIG_2(PByteArray.getCPtr(buffer)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public PByteArray GetByteArray() {
    PByteArray ret = new PByteArray(PapillonPINVOKE.PMemoryStream_GetByteArray(swigCPtr), true);
    return ret;
  }

  public PResult WriteObjectDescription(PDescription t) {
    PResult ret = new PResult(PapillonPINVOKE.PMemoryStream_WriteObjectDescription(swigCPtr, PDescription.getCPtr(t)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PResult ReadObjectDescription(PDescription t) {
    PResult ret = new PResult(PapillonPINVOKE.PMemoryStream_ReadObjectDescription(swigCPtr, PDescription.getCPtr(t)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
