//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PPolygoni : PObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PPolygoni(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PapillonPINVOKE.PPolygoni_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PPolygoni obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PPolygoni() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PapillonPINVOKE.delete_PPolygoni(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public PPolygoni(VectorPoint2Di points) : this(PapillonPINVOKE.new_PPolygoni__SWIG_0(VectorPoint2Di.getCPtr(points)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public PPolygoni() : this(PapillonPINVOKE.new_PPolygoni__SWIG_1(), true) {
  }

  public PPolygoni(PRectanglei r) : this(PapillonPINVOKE.new_PPolygoni__SWIG_2(PRectanglei.getCPtr(r)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public PPolygoni(PPolygoni other) : this(PapillonPINVOKE.new_PPolygoni__SWIG_3(PPolygoni.getCPtr(other)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    PapillonPINVOKE.PPolygoni_Clear(swigCPtr);
  }

  public bool IsEmpty() {
    bool ret = PapillonPINVOKE.PPolygoni_IsEmpty(swigCPtr);
    return ret;
  }

  public int Size() {
    int ret = PapillonPINVOKE.PPolygoni_Size(swigCPtr);
    return ret;
  }

  public PPoint2Di GetPoint(int index) {
    PPoint2Di ret = new PPoint2Di(PapillonPINVOKE.PPolygoni_GetPoint(swigCPtr, index), true);
    return ret;
  }

  public PPoint2Di GetFirstPoint() {
    PPoint2Di ret = new PPoint2Di(PapillonPINVOKE.PPolygoni_GetFirstPoint(swigCPtr), true);
    return ret;
  }

  public PPoint2Di GetLastPoint() {
    PPoint2Di ret = new PPoint2Di(PapillonPINVOKE.PPolygoni_GetLastPoint(swigCPtr), true);
    return ret;
  }

  public PRectanglei GetBoundingRectangle() {
    PRectanglei ret = new PRectanglei(PapillonPINVOKE.PPolygoni_GetBoundingRectangle(swigCPtr), true);
    return ret;
  }

  public PPolygoni GetConvexHull() {
    PPolygoni ret = new PPolygoni(PapillonPINVOKE.PPolygoni_GetConvexHull(swigCPtr), true);
    return ret;
  }

  public void SetPoint(int index, PPoint2Di pt) {
    PapillonPINVOKE.PPolygoni_SetPoint(swigCPtr, index, PPoint2Di.getCPtr(pt));
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public PPolygoni AddPoint(int x, int y, int index) {
    PPolygoni ret = new PPolygoni(PapillonPINVOKE.PPolygoni_AddPoint__SWIG_0(swigCPtr, x, y, index), false);
    return ret;
  }

  public PPolygoni AddPoint(int x, int y) {
    PPolygoni ret = new PPolygoni(PapillonPINVOKE.PPolygoni_AddPoint__SWIG_1(swigCPtr, x, y), false);
    return ret;
  }

  public PPolygoni AddPoint(PPoint2Di pt, int index) {
    PPolygoni ret = new PPolygoni(PapillonPINVOKE.PPolygoni_AddPoint__SWIG_2(swigCPtr, PPoint2Di.getCPtr(pt), index), false);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PPolygoni AddPoint(PPoint2Di pt) {
    PPolygoni ret = new PPolygoni(PapillonPINVOKE.PPolygoni_AddPoint__SWIG_3(swigCPtr, PPoint2Di.getCPtr(pt)), false);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PPolygoni Intersected(PPolygoni other) {
    PPolygoni ret = new PPolygoni(PapillonPINVOKE.PPolygoni_Intersected(swigCPtr, PPolygoni.getCPtr(other)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PPolygoni United(PPolygoni other) {
    PPolygoni ret = new PPolygoni(PapillonPINVOKE.PPolygoni_United(swigCPtr, PPolygoni.getCPtr(other)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
