//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PProperties : PStringMap {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PProperties(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PapillonPINVOKE.PProperties_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PProperties obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PProperties() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PapillonPINVOKE.delete_PProperties(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static PProperties Empty() {
    PProperties ret = new PProperties(PapillonPINVOKE.PProperties_Empty(), false);
    return ret;
  }

  public PProperties() : this(PapillonPINVOKE.new_PProperties__SWIG_0(), true) {
  }

  public PProperties(PProperties other) : this(PapillonPINVOKE.new_PProperties__SWIG_1(PProperties.getCPtr(other)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public static PProperties CreateFromKeyValueString(string s) {
    PProperties ret = new PProperties(PapillonPINVOKE.PProperties_CreateFromKeyValueString(s), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PProperties Set(string key, PObject value) {
    PProperties ret = new PProperties(PapillonPINVOKE.PProperties_Set__SWIG_0(swigCPtr, key, PObject.getCPtr(value)), false);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PProperties Set(string key, string value) {
    PProperties ret = new PProperties(PapillonPINVOKE.PProperties_Set__SWIG_1(swigCPtr, key, value), false);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PProperties Set(string key, bool value) {
    PProperties ret = new PProperties(PapillonPINVOKE.PProperties_Set__SWIG_2(swigCPtr, key, value), false);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PProperties Set(string key, int value) {
    PProperties ret = new PProperties(PapillonPINVOKE.PProperties_Set__SWIG_3(swigCPtr, key, value), false);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PProperties Set(string key, long value) {
    PProperties ret = new PProperties(PapillonPINVOKE.PProperties_Set__SWIG_4(swigCPtr, key, value), false);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PProperties Set(string key, float value) {
    PProperties ret = new PProperties(PapillonPINVOKE.PProperties_Set__SWIG_5(swigCPtr, key, value), false);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PProperties Set(string key, double value) {
    PProperties ret = new PProperties(PapillonPINVOKE.PProperties_Set__SWIG_6(swigCPtr, key, value), false);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetBool(string key, ref bool ok) {
    bool ret = PapillonPINVOKE.PProperties_GetBool__SWIG_0(swigCPtr, key, ref ok);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetBool(string key) {
    bool ret = PapillonPINVOKE.PProperties_GetBool__SWIG_1(swigCPtr, key);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetInt32(string key, ref bool ok) {
    int ret = PapillonPINVOKE.PProperties_GetInt32__SWIG_0(swigCPtr, key, ref ok);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetInt32(string key) {
    int ret = PapillonPINVOKE.PProperties_GetInt32__SWIG_1(swigCPtr, key);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public long GetInt64(string key, ref bool ok) {
    long ret = PapillonPINVOKE.PProperties_GetInt64__SWIG_0(swigCPtr, key, ref ok);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public long GetInt64(string key) {
    long ret = PapillonPINVOKE.PProperties_GetInt64__SWIG_1(swigCPtr, key);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float GetFloat(string key, ref bool ok) {
    float ret = PapillonPINVOKE.PProperties_GetFloat__SWIG_0(swigCPtr, key, ref ok);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public float GetFloat(string key) {
    float ret = PapillonPINVOKE.PProperties_GetFloat__SWIG_1(swigCPtr, key);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetDouble(string key, ref bool ok) {
    double ret = PapillonPINVOKE.PProperties_GetDouble__SWIG_0(swigCPtr, key, ref ok);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double GetDouble(string key) {
    double ret = PapillonPINVOKE.PProperties_GetDouble__SWIG_1(swigCPtr, key);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetAsString(string name) {
    string ret = PapillonPINVOKE.PProperties_GetAsString(swigCPtr, name);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int RemoveByRegexp(string pattern) {
    int ret = PapillonPINVOKE.PProperties_RemoveByRegexp(swigCPtr, pattern);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string ToStringLog() {
    string ret = PapillonPINVOKE.PProperties_ToStringLog(swigCPtr);
    return ret;
  }

}
