//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PStoreIterator : PObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PStoreIterator(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PapillonPINVOKE.PStoreIterator_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PStoreIterator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PStoreIterator() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PapillonPINVOKE.delete_PStoreIterator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public PStoreIterator() : this(PapillonPINVOKE.new_PStoreIterator__SWIG_0(), true) {
  }

  public PStoreIterator(PStoreIterator other) : this(PapillonPINVOKE.new_PStoreIterator__SWIG_1(PStoreIterator.getCPtr(other)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public PResult Next() {
    PResult ret = new PResult(PapillonPINVOKE.PStoreIterator_Next(swigCPtr), true);
    return ret;
  }

  public PEntity GetEntity() {
    PEntity ret = new PEntity(PapillonPINVOKE.PStoreIterator_GetEntity(swigCPtr), true);
    return ret;
  }

  public PResult Get(PObject arg0) {
    PResult ret = new PResult(PapillonPINVOKE.PStoreIterator_Get(swigCPtr, PObject.getCPtr(arg0)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
