//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PUInt16 : PObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PUInt16(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PapillonPINVOKE.PUInt16_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PUInt16 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PUInt16() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PapillonPINVOKE.delete_PUInt16(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public PUInt16(ushort value) : this(PapillonPINVOKE.new_PUInt16__SWIG_0(value), true) {
  }

  public PUInt16() : this(PapillonPINVOKE.new_PUInt16__SWIG_1(), true) {
  }

  public PUInt16(PUInt16 other) : this(PapillonPINVOKE.new_PUInt16__SWIG_2(PUInt16.getCPtr(other)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public ushort GetValue() {
    ushort ret = PapillonPINVOKE.PUInt16_GetValue(swigCPtr);
    return ret;
  }

}
