//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PVerify : PObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PVerify(global::System.IntPtr cPtr, bool cMemoryOwn) : base(PapillonPINVOKE.PVerify_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PVerify obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PVerify() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PapillonPINVOKE.delete_PVerify(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public PVerify() : this(PapillonPINVOKE.new_PVerify__SWIG_0(), true) {
  }

  public PVerify(PEnrollment enrollment, EVerificationSecurityLevel securityLevel, double threshold) : this(PapillonPINVOKE.new_PVerify__SWIG_1(PEnrollment.getCPtr(enrollment), (int)securityLevel, threshold), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public PVerify(PEnrollment enrollment, EVerificationSecurityLevel securityLevel) : this(PapillonPINVOKE.new_PVerify__SWIG_2(PEnrollment.getCPtr(enrollment), (int)securityLevel), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public PVerify(PEnrollment enrollment) : this(PapillonPINVOKE.new_PVerify__SWIG_3(PEnrollment.getCPtr(enrollment)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public PVerify(PVerify other) : this(PapillonPINVOKE.new_PVerify__SWIG_4(PVerify.getCPtr(other)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsConfigured() {
    bool ret = PapillonPINVOKE.PVerify_IsConfigured(swigCPtr);
    return ret;
  }

  public EVerificationSecurityLevel GetSecurityLevel(SWIGTYPE_p_double threshold) {
    EVerificationSecurityLevel ret = (EVerificationSecurityLevel)PapillonPINVOKE.PVerify_GetSecurityLevel(swigCPtr, SWIGTYPE_p_double.getCPtr(threshold));
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PResult SetSecurityLevel(EVerificationSecurityLevel securityLevel, double threshold) {
    PResult ret = new PResult(PapillonPINVOKE.PVerify_SetSecurityLevel__SWIG_0(swigCPtr, (int)securityLevel, threshold), true);
    return ret;
  }

  public PResult SetSecurityLevel(EVerificationSecurityLevel securityLevel) {
    PResult ret = new PResult(PapillonPINVOKE.PVerify_SetSecurityLevel__SWIG_1(swigCPtr, (int)securityLevel), true);
    return ret;
  }

  public PResult VerifyFromDescription(PDescription description1, PDescription description2, PMatchScore matchScore) {
    PResult ret = new PResult(PapillonPINVOKE.PVerify_VerifyFromDescription(swigCPtr, PDescription.getCPtr(description1), PDescription.getCPtr(description2), PMatchScore.getCPtr(matchScore)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PResult VerifyFromDescriptionFile(string descriptionFile1, string descriptionFile2, PMatchScore matchScore) {
    PResult ret = new PResult(PapillonPINVOKE.PVerify_VerifyFromDescriptionFile(swigCPtr, descriptionFile1, descriptionFile2, PMatchScore.getCPtr(matchScore)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PResult VerifyFromImage(PImage image1, PImage image2, PMatchScore matchScore, PDescription outputDescription1, PDescription outputDescription2) {
    PResult ret = new PResult(PapillonPINVOKE.PVerify_VerifyFromImage(swigCPtr, PImage.getCPtr(image1), PImage.getCPtr(image2), PMatchScore.getCPtr(matchScore), PDescription.getCPtr(outputDescription1), PDescription.getCPtr(outputDescription2)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PResult VerifyFromImageFile(string imageFilename1, string imageFilename2, PMatchScore matchScore, PDescription outputDescription1, PDescription outputDescription2) {
    PResult ret = new PResult(PapillonPINVOKE.PVerify_VerifyFromImageFile(swigCPtr, imageFilename1, imageFilename2, PMatchScore.getCPtr(matchScore), PDescription.getCPtr(outputDescription1), PDescription.getCPtr(outputDescription2)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PResult VerifyFromVideoFile(PDescription description, string videoFilename, PMatchScore matchScore, PDescription outputDescription, int maxFrames, int maxExamples) {
    PResult ret = new PResult(PapillonPINVOKE.PVerify_VerifyFromVideoFile__SWIG_0(swigCPtr, PDescription.getCPtr(description), videoFilename, PMatchScore.getCPtr(matchScore), PDescription.getCPtr(outputDescription), maxFrames, maxExamples), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PResult VerifyFromVideoFile(PDescription description, string videoFilename, PMatchScore matchScore, PDescription outputDescription, int maxFrames) {
    PResult ret = new PResult(PapillonPINVOKE.PVerify_VerifyFromVideoFile__SWIG_1(swigCPtr, PDescription.getCPtr(description), videoFilename, PMatchScore.getCPtr(matchScore), PDescription.getCPtr(outputDescription), maxFrames), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PResult VerifyFromVideoFile(PDescription description, string videoFilename, PMatchScore matchScore, PDescription outputDescription) {
    PResult ret = new PResult(PapillonPINVOKE.PVerify_VerifyFromVideoFile__SWIG_2(swigCPtr, PDescription.getCPtr(description), videoFilename, PMatchScore.getCPtr(matchScore), PDescription.getCPtr(outputDescription)), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
