//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VectorDescription : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IEnumerable<PDescription>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VectorDescription(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VectorDescription obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VectorDescription() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          PapillonPINVOKE.delete_VectorDescription(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public VectorDescription(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (PDescription element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public PDescription this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(PDescription[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(PDescription[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, PDescription[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<PDescription> global::System.Collections.Generic.IEnumerable<PDescription>.GetEnumerator() {
    return new VectorDescriptionEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new VectorDescriptionEnumerator(this);
  }

  public VectorDescriptionEnumerator GetEnumerator() {
    return new VectorDescriptionEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class VectorDescriptionEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<PDescription>
  {
    private VectorDescription collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public VectorDescriptionEnumerator(VectorDescription collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public PDescription Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (PDescription)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    PapillonPINVOKE.VectorDescription_Clear(swigCPtr);
  }

  public void Add(PDescription x) {
    PapillonPINVOKE.VectorDescription_Add(swigCPtr, PDescription.getCPtr(x));
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = PapillonPINVOKE.VectorDescription_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = PapillonPINVOKE.VectorDescription_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    PapillonPINVOKE.VectorDescription_reserve(swigCPtr, n);
  }

  public VectorDescription() : this(PapillonPINVOKE.new_VectorDescription__SWIG_0(), true) {
  }

  public VectorDescription(VectorDescription other) : this(PapillonPINVOKE.new_VectorDescription__SWIG_1(VectorDescription.getCPtr(other)), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDescription(int capacity) : this(PapillonPINVOKE.new_VectorDescription__SWIG_2(capacity), true) {
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  private PDescription getitemcopy(int index) {
    PDescription ret = new PDescription(PapillonPINVOKE.VectorDescription_getitemcopy(swigCPtr, index), true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private PDescription getitem(int index) {
    PDescription ret = new PDescription(PapillonPINVOKE.VectorDescription_getitem(swigCPtr, index), false);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, PDescription val) {
    PapillonPINVOKE.VectorDescription_setitem(swigCPtr, index, PDescription.getCPtr(val));
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(VectorDescription values) {
    PapillonPINVOKE.VectorDescription_AddRange(swigCPtr, VectorDescription.getCPtr(values));
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public VectorDescription GetRange(int index, int count) {
    global::System.IntPtr cPtr = PapillonPINVOKE.VectorDescription_GetRange(swigCPtr, index, count);
    VectorDescription ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorDescription(cPtr, true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, PDescription x) {
    PapillonPINVOKE.VectorDescription_Insert(swigCPtr, index, PDescription.getCPtr(x));
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, VectorDescription values) {
    PapillonPINVOKE.VectorDescription_InsertRange(swigCPtr, index, VectorDescription.getCPtr(values));
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    PapillonPINVOKE.VectorDescription_RemoveAt(swigCPtr, index);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    PapillonPINVOKE.VectorDescription_RemoveRange(swigCPtr, index, count);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public static VectorDescription Repeat(PDescription value, int count) {
    global::System.IntPtr cPtr = PapillonPINVOKE.VectorDescription_Repeat(PDescription.getCPtr(value), count);
    VectorDescription ret = (cPtr == global::System.IntPtr.Zero) ? null : new VectorDescription(cPtr, true);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    PapillonPINVOKE.VectorDescription_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    PapillonPINVOKE.VectorDescription_Reverse__SWIG_1(swigCPtr, index, count);
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, VectorDescription values) {
    PapillonPINVOKE.VectorDescription_SetRange(swigCPtr, index, VectorDescription.getCPtr(values));
    if (PapillonPINVOKE.SWIGPendingException.Pending) throw PapillonPINVOKE.SWIGPendingException.Retrieve();
  }

}
